version: '3.8'

services:
  app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile.dev
    volumes:
      - ..:/workspace:cached
    command: sleep infinity
    network_mode: service:db
    environment:
      DATABASE_URL: postgresql://flightlog:dev_password@localhost:5432/flightlog_dev
      NODE_ENV: development
    
  db:
    image: postgres:16-alpine
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: flightlog
      POSTGRES_PASSWORD: dev_password
      POSTGRES_DB: flightlog_dev
    ports:
      - "5432:5432"

volumes:
  postgres-data:
